### ISSUE TITLE
How to use shodan search query in leaklooker?

### ISSUE THREAD

**Issue by chungtra** [woj-ciech/LeakLooker#8]
Hi friend,

can you please help me how can we use shodan search filters in Leaklooker like country/City/Org filter.

Regards

**Comment by k3v142** [comment]
https://github.com/woj-ciech/LeakLooker/blob/0d2b9fc1fbd09151e67b494a17d07a72a3452b18/leaklooker.py#L73-L88

This is the function where the search query is executing. Right now `LeakLooker` doesn't support additional search parameters, but if @woj-ciech will merge my pull requests I could do it for you because I think it would be useful for others too.

**Comment by chungtra** [comment]
This would be a great help for everybody and for the time being we have to manually edit the script with custom shodan query to search here:

query_elastic = 'product:elastic port:9200 '
query_mongodb = 'product:MongoDB '
query_couchdb = "product:couchdb "
query_kibana = "kibana content-length: 217

**Comment by Ahmadkifre** [comment]
i have this problem   
File "leaklooker.py", line 321
    modules = [*service['rsync']['modules']]
               ^
SyntaxError: invalid syntax

**Comment by woj-ciech** [comment]
@k3v142 custom search is present in new version, thanks.
@Ahmadkifre use python 3
